trigger:
- master
- develop

pr:
  branches:
    include:
    - '*'

strategy:
  matrix:
    Cliqz:
      scheme: 'Cliqz'
      actions: 'build'
    Ghostery:
      scheme: 'Ghostery'
      actions: 'build'
    CliqzTests:
      scheme: 'Cliqz'
      actions: 'test'

pool:
  vmImage: 'macOS-10.15'

steps:
- bash: |
    sudo xcode-select --switch /Applications/Xcode_12.app
  displayName: 'Change XCode to 12'

- task: NodeTool@0
  displayName: 'Define Node to v12.18.4'
  inputs:
    versionSpec: '12.18.4'

- bash: |
    set -x
    npm i -g npm@6.5
    /usr/local/bin/npm ci
  displayName: 'Install Node modules'

- bash: |
    set -x
    npm run build-user-scripts
  displayName: Generate User Scripts

- task: UseRubyVersion@0
  inputs:
    versionSpec: '2.6'
    addToPath: true

- bash: |
    set -x
    gem install bundler:2.1.4 --force
    bundle install --retry=3
    bundle exec pod repo update
    bundle exec pod install
  displayName: 'Install CocoaPods'

- bash: bundle exec fastlane lint
  displayName: 'Lint'

- task: Xcode@5
  inputs:
    actions: '$(actions)'
    sdk: 'iphonesimulator'
    xcWorkspacePath: 'UserAgent.xcworkspace'
    scheme: '$(scheme)'
    packageApp: true
    configuration: 'CI'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 11'
    publishJUnitResults: true
    args: '-derivedDataPath builds'
